Bhaptics vest integration
brandonmousseau/vhvr-mod pull request #184
Opened 2022-03-28 18:54 UTC by Astienth

Bhaptics support integration:

- BhapticsTactsuit.cs is the vibration patterns player, sending to pc bhaptics client
- BhapticsPatches.cs are all the harmony hooks
- a folder called bHaptics contains all the tact files needed for the vest. They are the vibration patterns
- the bhaptics library is added with all the tact files in the make-release.cmd

Functionalities:

The tactsuit only initializes in vr mode and is disabled by default in the config file. On different events, vibration patterns are thrown that can be a single effect or a repeating effect.
All the functionalities are in the harmony hooks in BhapticsPatches.cs.

Weak points in the code : 

I had to add a variable in the Weaponcollision script : https://github.com/Astienth/vhvr-mod/blob/bhaptics/ValheimVRMod/Scripts/WeaponCollision.cs#L29
Many bhapticsPatches methods are hooked in the vr mod scripts methods. I don't know if it is a bad behaviour.
The intent of that was to come after any vr logic. For example https://github.com/Astienth/vhvr-mod/blob/5b777cbe5e81c5eadfda20c55649874db23b210e/ValheimVRMod/Patches/BHapticsPatches.cs#L186, getting the arrow from your back which doesn't exist in the original code.

2022-03-28 20:50 UTC, brandonmousseau requested changes
Thanks again for adding this support, motivates me to want to get a vest :)

I have a few requests for changes but overall looks good.

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            switch (hlth)
nit comment: no need to change this if you don't want to, as its effectively the same, but I'd rather just see if/else rather than a switch statement

eg
```cs
if (health < 20 && hlth >15) {
    TactsuitVR.StopThreadHaptic("HeartBeatFast");
    TactsuitVR.StartThreadHaptic("HeartBeat");
} else if (hlth <= 15 && hlth >0) {
    TactsuitVR.StopThreadHaptic("HeartBeat");
    TactsuitVR.StartThreadHaptic("HeartBeatFast", 1.0f, false, 0);
} else if (hlth <= 0) {
    TactsuitVR.StopThreadHaptic("HeartBeat");
    TactsuitVR.StopThreadHaptic("HeartBeatFast");
    TactsuitVR.PlaybackHaptics("Death");
} else {
    TactsuitVR.StopThreadHaptic("HeartBeat");
    TactsuitVR.StopThreadHaptic("HeartBeatFast");
}
```

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.PlaybackHaptics("Death");
Is this conflicting/duplicate with the "SetHealth" patch that also executes the Death haptic?

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.StopAllHapticFeedback();
Just for my understanding, in the Prefix, you start a haptic feedback playback, then here in the postfix, you call this method. Will `StopAllHapticFeedback` also stop the feedback started in the prefix?

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                    //are we in env rain starting delay ?
just for my own understanding, you could explain what the start delay stuff is about? is it something to do with the game "starting" the rain effect, but not actually being raining yet?

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +    public class TactsuitVR : MonoBehaviour
Can you make the class/file name the same?

2022-03-28 20:50 UTC, brandonmousseau commented on ValheimVRMod/Scripts/WeaponCollision.cs
> +        private bool hasAttackedSuccess;
Is this used anywhere? Seems it's set to true/false but not read anywhere else.

2022-03-28 21:08 UTC, brandonmousseau requested changes

2022-03-28 21:08 UTC, brandonmousseau commented on ValheimVRMod/Utilities/VHVRConfig.cs
> +            return bhapticsEnabled.Value;
might be worth enforcing the other condition you have on this from the description - particularly the nonVrPlayer, so that even if the config is messed up it'll still work properly:
```cs
return bhapticsEnabled.Value && !NonVrPlayer()
```

2022-03-28 21:15 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            if (__instance != Player.m_localPlayer || EquipScript.getLeft() != EquipType.Shield || !VHVRConfig.UseVrControls())
do we need to add ` TactsuitVR.suitDisabled` here?

2022-03-28 21:20 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                TactsuitVR.StopThreadHaptic("Teleporting", new string[] {"PassPortalBack", "PassPortalTactosy"});
What happens if you call "StopThreadHaptic" without first having called "StartThreadHaptic"?

2022-03-28 21:31 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                Thread.Sleep(2000);
Won't this sleep the main thread?

2022-03-28 21:37 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                TactsuitVR.PlaybackHaptics(VHVRConfig.LeftHanded() ? "Petting_L" : "Petting_R");
I think we can leave this how it is for now - but actually interaction can be done with either hand, regardless of the LefHanded setting (Left handed stuff is fairly buggy atm too, but thats a separate thing). It'd be nice if we can figure out which hand actually did the interaction - but we'll probably need to add in some hook to be able to determine that.

BTW: does this haptic just go to the controller or is there some separate bhaptics device that is triggered?

2022-03-28 21:53 UTC, brandonmousseau commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +        public static KeyValuePair<float, float> getAngleAndShift(Player player, Vector3 hit)
I wonder if a Tuple might be more appropriate as the return datatype here
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/value-tuples
or even some custom data type.

While KeyValuePair works here, it might be confusing in the future since it's intent is to be used as something that would exist in a Dictionary where the the key is used to lookup the value - whereas in this case, we just want a pair of numbers to be returned.

2022-03-29 05:51 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +    [HarmonyPatch(typeof(BowManager), "pullString")]
Done

2022-03-29 05:54 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            switch (hlth)
Done

2022-03-29 05:58 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.PlaybackHaptics("Death");
I think it is redundant indeed, removed death effect from setHealth patch. The point of the setHealth patch case <= 0 was to stop the threads if anything goes wrong. Death effect should be triggered OnDeath anyway.

2022-03-29 06:03 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.StopAllHapticFeedback();
In the prefix is the death effect. On the postfix is only to stop all threads effects. For example, when you die, it is to make sure no effects are still running like low health, status effects, riding lox, etc. The prefix effect is not a thread so it will be executed properly.

2022-03-29 06:04 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                    //are we in env rain starting delay ?
That's exactly that, I added some comment on the property.

2022-03-29 06:10 UTC, Astienth commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +    public class TactsuitVR : MonoBehaviour
Done

2022-03-29 06:11 UTC, Astienth commented on ValheimVRMod/Scripts/WeaponCollision.cs
> +        private bool hasAttackedSuccess;
I used it in a patch that is now directly in this file. I removed this property

2022-03-29 06:12 UTC, Astienth commented on ValheimVRMod/Utilities/VHVRConfig.cs
> +            return bhapticsEnabled.Value;
Done

2022-03-29 06:14 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            if (__instance != Player.m_localPlayer || EquipScript.getLeft() != EquipType.Shield || !VHVRConfig.UseVrControls())
You're absolutely right, my bad Oo. Done

2022-03-29 06:29 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                TactsuitVR.StopThreadHaptic("Teleporting", new string[] {"PassPortalBack", "PassPortalTactosy"});
It should be safe to call "StopThreadHaptic" without having called "StartThreadHaptic" as it only stops an active thread.
I removed the prefix and it seems to be working. :)

2022-03-29 06:36 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.StopAllHapticFeedback();
Got it, thanks!

2022-03-29 07:01 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                Thread.Sleep(2000);
I guess that's what should happen but I tested it, crossing a portal while having status effect (which is a thread) and it doesn't stop any thread. I tested it without "Tread.sleep(2000)" and using the last parameter of "StartThreadHaptic", it behaves the same. I'll keep it with the last parameter.

2022-03-29 07:05 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +                TactsuitVR.PlaybackHaptics(VHVRConfig.LeftHanded() ? "Petting_L" : "Petting_R");
Oh right, I was getting used to use VHVRConfig.LeftHanded. I guess left handed people are more likely to use their left hand to do things. Thought indeed, like that it doesn't really works. 
Tactosy is a separate device consisting in two arms devices: left and right. It is a separated device from the vest.
The petting effect isn't really relevant anyway. I think it's ok like that. It's just a little plus on action. It was actually a request from a fellow developer from the bhaptics discord when I asked if anyone had any ideas of effects. :)

2022-03-29 07:07 UTC, Astienth commented
Thanks for your help, I have fixed many issues but not all of them. I'll push them anyway but won't be able to test and fix everything today. Be right back to it as soon as possible.

2022-03-29 07:52 UTC, Astienth commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +        public static KeyValuePair<float, float> getAngleAndShift(Player player, Vector3 hit)
I totally agree with you. Though using tuple seems to require a nuget package and doesn't seem to work properly, at least I haven't been able to make it work. If you can add the package necessary to use tuples, can you tell me how to do it ? Otherwise how abuot just an array of float ?

2022-03-29 14:03 UTC, Astienth commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.StopAllHapticFeedback();
I was wrong about this point, It stopped the death effect indeed. I fixed it to add exceptions in StopAllHapticFeedback. tested ok.

2022-03-29 16:13 UTC, brandonmousseau commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +        public static KeyValuePair<float, float> getAngleAndShift(Player player, Vector3 hit)
Ah, I see - an array of floats would be fine with me too. Another option would just be to create your own custom data class here and use it. Just a short definition, something like this (with whatever name you think is best, I just picked a dummy name). 

```cs
public class MyHitData {
    public float angle;
    public float shift;

    public MyHitData(float hitAngle, float hitShift) {
       angle = hitAngle;
       shift = hitShift;
    }
}
```

Doing things this way has the extra benefit that it helps self document what the `getAngleAndShift` method is used for.

2022-03-29 16:15 UTC, brandonmousseau commented on ValheimVRMod/ValheimVRMod.csproj
> +	<PropertyGroup>
yep, thanks!

2022-03-29 16:17 UTC, brandonmousseau commented on ValheimVRMod/Patches/BHapticsPatches.cs
> +            TactsuitVR.StopAllHapticFeedback();
Ok, thanks!

2022-03-29 17:09 UTC, Astienth commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +        public static KeyValuePair<float, float> getAngleAndShift(Player player, Vector3 hit)
Done, the name is fine, self explanatory :)

2022-03-29 18:43 UTC, brandonmousseau commented on ValheimVRMod/Scripts/BhapticsTactsuit.cs
> +        public static KeyValuePair<float, float> getAngleAndShift(Player player, Vector3 hit)
nice, looks good

2022-03-29 18:44 UTC, brandonmousseau approved these changes

2022-03-29 18:48 UTC, merged