Add Roomscale Sneak
brandonmousseau/vhvr-mod pull request #84
Opened 2021-06-29 06:19 UTC by Aceship

+ Add Roomscale sneak
+ Add Roomscale sneak option (Enabling and Height of sneaking)

- currently disable running while roomscale sneaking
- still can attack while sneaking

2021-06-29 13:50 UTC, brandonmousseau requested changes

2021-06-29 13:50 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +            if (camera.localPosition.y < VHVRConfig.RoomScaleSneakHeight()) {
One thing we have access to is this:
```cs
float height = Valve.VR.InteractionSystem.Player.instance.eyeHeight;
```

This should give a more accurate position of actual player height I *think* (at least according to documentation). What we can do is in ```maybeInitHeadPosition``` is save that value off when the head position is initialized to get a reference height. Then in this function, we can compare it to a percentage of this value. The config file option can be a percentage of the player's height, so in theory it should work automatically for players of different heights.

```cs
float currentHeight = Valve.VR.InteractionSystem.Player.instance.eyeHeight;
if (currentHeight < referenceHeight * someConfiguredPercentage) {
   ...
}
```

The other thing is that we may want to include a dead zone to prevent the player from accidentally flipping back and forth between crouching and not crouching rapidly if they are right on the edge of the trigger. So what I mean is, lets say we configure the setpoint to trigger crouching to be 50%. The logic would be:
If the player is standing and drops below 50%, then we switch to crouching. But the player must go back above 55% in order to trigger standing back up. This way if the player is kind crouching but shifts a bit between 50%-51% but didn't intend to stand up, standing back up won't be unintentionally triggered.

50% and 55% were just examples, so the crouch percentage would be whatever configured percentage is in the config file and the "stand back up" percentage would be that plus some small deadzone, but 5-10% seems reasonable.

2021-06-29 13:50 UTC, brandonmousseau commented on ValheimVRMod/Utilities/VHVRConfig.cs
> +            roomScaleSneakHeight = config.Bind("Controls",
As I mentioned in the other class, I think this should be a percentage and we should try and determine player height programmatically which I hope will work more out of the box without players needing to adjust this. If we make it a percentage, we'd want to restrict the value between an appropriate range. See ```overlayCurvature``` for how to restrict config file input values between a range.

2021-06-29 13:50 UTC, brandonmousseau commented on ValheimVRMod/Patches/ControlPatches.cs
> +            if (VHVRConfig.RoomScaleSneakEnabled()) {
This patch seems to be getting pretty large. I wonder if we can refactor it out into a separate patch. At least the logic related to running/crouching and the Equip stuff seem to not be related to each other (maybe @Andi1986 can confirm if that's not the case).

2021-06-29 13:50 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +        public static bool isSneaking = false;
[Minor] We should change variables like this to be properties with only getters to avoid having external classes accidentally set them (and it communicates to external classes that they aren't supposed to set it).

```cs
private static bool _isSneaking = false;
public static bool isSneaking { get { return _isSneaking } };
```
Internal logic can just set _isSneaking then external classes that need the info would just have access to get the property.

2021-06-29 13:50 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +            if (VHVRConfig.RoomScaleSneakEnabled()) {
[Nit] Can you move this config file check to inside the ```CheckSneakRoomscale``` function and return early instead (just to keep consistency with the rest of this function.

2021-06-29 15:09 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +            if (VHVRConfig.RoomScaleSneakEnabled()) {
Done for this one (on next push) 👍

2021-06-29 15:10 UTC, Aceship commented on ValheimVRMod/Utilities/VHVRConfig.cs
> +            roomScaleSneakHeight = config.Bind("Controls",
Done for this one (on next push) 👍

2021-06-29 15:10 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +            if (camera.localPosition.y < VHVRConfig.RoomScaleSneakHeight()) {
Done for this one (on next push) 👍

2021-06-29 15:21 UTC, Aceship commented on ValheimVRMod/Patches/ControlPatches.cs
> +            if (VHVRConfig.RoomScaleSneakEnabled()) {
i think it may need seperate patch since its larger now

2021-06-29 15:21 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +        public static bool isSneaking = false;
about this one, it might need checking new one, its changed and probably might need new review especially i used it weirdly

2021-06-29 15:30 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +        public static bool isNonRSSneaking = false;
@brandonmousseau about this one , the `isNonRSSneaking` is being changed on patches , idk if its a good idea or not

2021-06-29 15:58 UTC, brandonmousseau requested changes

2021-06-29 15:58 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +        private static float initHeadPos;
Can we rename this to something like `referencePlayerHeight` ?

2021-06-29 15:58 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +                else {
I still would like to see some logic that implements the "deadzone" - where if the player drops below ```RoomScaleSneakHeight%```, they will enter sneak mode, but in order to go back standing up, they need to rise to something like ```RoomScaleSneakHeight% + 5%``` or something. This is to avoid rapid flipping between crouching and standing if the player is kinda on the edge of the trip point.

2021-06-29 16:59 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +                else {
added on new push

2021-06-29 16:59 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +        private static float initHeadPos;
done on new push 👌

2021-07-01 23:33 UTC, brandonmousseau requested changes

2021-07-01 23:33 UTC, brandonmousseau commented on ValheimVRMod/VRCore/VRPlayer.cs
> +                if (!VHVRConfig.RoomScaleSneakEnabled()|| isNonRSSneaking) {
This always returns CROUCH_HEIGHT_ADJUST when room scale sneak is disabled. Should be
```cs
if (!VHVRConfig.RoomScaleSneakEnabled() && isNonRSSneaking)
```
I think.

2021-07-01 23:33 UTC, brandonmousseau commented on ValheimVRMod/Patches/ControlPatches.cs
> +                    else if(!VRPlayer.isRoomscaleSneak && player.IsCrouching()&&wasCrouching) {
nit:  general comment about whitespace:
```cs
player.IsCrouching()&&wasCrouching
```
--->
```cs
player.IsCrouching() && wasCrouching
```

2021-07-01 23:33 UTC, brandonmousseau commented on ValheimVRMod/Patches/ControlPatches.cs
> +                if (ZInput_GetJoyRightStickY_Patch.isCrouching) {
a general question:
It looks like you are trying to simultaneously support roomscale sneak and regular controller input sneak. I guess it's just a general question of "is that necessary?" Seems like it may complicate things unnecessarily but I suppose players may want to have both simultaneously potentially?

2021-07-01 23:33 UTC, brandonmousseau commented on ValheimVRMod/Patches/ControlPatches.cs
> +                        if (!wasNonRSCrouching) {
this could be just:
```cs
if (!VRPlayer.isRoomscaleSneak && !wasNonRSCrouching)
```

instead of the nested statement.

2021-07-01 23:33 UTC, brandonmousseau commented on ValheimVRMod/Patches/ControlPatches.cs
>          static void Prefix(Player __instance, ref bool attack, ref bool attackHold, ref bool block, ref bool blockHold,
I still think we should split this into multiple patches/refactor it some more but I'm okay if we do that in a follow-on change.

2021-07-02 08:24 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +                if (!VHVRConfig.RoomScaleSneakEnabled()|| isNonRSSneaking) {
yeah, but it only check if check while character is crouching, so its always offset head while crouching with roomscale sneak turned off

2021-07-02 08:30 UTC, Aceship commented on ValheimVRMod/Patches/ControlPatches.cs
> +                if (ZInput_GetJoyRightStickY_Patch.isCrouching) {
yeah it supports both roomscale and input sneak, someone would have actual sneak toggle input
especially if the roomscale sneak option wanna be turned on by default, people might confused why the sneak input doesn't work

2021-07-02 08:39 UTC, Aceship commented on ValheimVRMod/VRCore/VRPlayer.cs
> +            }
ah yeah it would be better that way, gonna add it

2021-07-02 08:42 UTC, Aceship commented on ValheimVRMod/Patches/ControlPatches.cs
> +                        if (!wasNonRSCrouching) {
done on newest push 👍

2021-07-02 08:42 UTC, Aceship commented on ValheimVRMod/Patches/ControlPatches.cs
> +                    else if(!VRPlayer.isRoomscaleSneak && player.IsCrouching()&&wasCrouching) {
done on newest push 👍

2021-07-02 08:43 UTC, Aceship commented on ValheimVRMod/Patches/ControlPatches.cs
>          static void Prefix(Player __instance, ref bool attack, ref bool attackHold, ref bool block, ref bool blockHold,
probably could be combined with later roomscale stuff when its available, since its a roomscale sneak

2021-07-02 14:08 UTC, merged